#!/usr/bin/env bash
# This script installs Nginx and serves a "Hello World!" page
# Installing nginx on the web-01

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service (no need for restart right away)
sudo service nginx start

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing (optional step)
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create the new "Hello World!" page
echo "Hello World!" > /var/www/html/index.html

# Reload Nginx (without using systemctl or service restart)
kill -HUP $(cat /var/run/nginx.pid)

echo -e "\nCompleted. ✅ Nginx is running and serving 'Hello World!'.\n"
