#!/usr/bin/env bash
# This script installs Nginx and serves a "Hello World!" page
# Installing nginx on the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
