#!/usr/bin/env bash
# A Bash script that prints "To infinity and beyond" indefinitely
# and responds to SIGTERM signal with "I am invincible!!!".

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' 15
done
