#!/usr/bin/env bash
# A script that tells the story of the users from /etc/passwd

# Define the IFS to split by colon
IFS=":"

# Read each line from /etc/passwd
while read -r username password user_id group_id user_info home_directory shell; do
  # Print the formatted output
  echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
