#!/usr/bin/env bash
# A script using a while loop to print Best School 10 times

var="Best School"
var2="Hi"
i=1

while [ "$i" -le 10 ]; do
    if [ "$i" -eq 10 ]; then
        echo "$var2"
    fi
    echo "$var"
    ((i++))
done
