#!/usr/bin/env bash
# A script using a while loop to print Best School 10 times

var="Best School"
i=0

while [ "$i" -lt 10 ]; do
	echo "$var"

	if [ "$i" -eq 9 ]; then
	echo "Hi"
	fi

	i=$((i + 1))
done
