#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
# Requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Write a Bash script that configures the container to fit the above requirements

sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf

if pgrep apache2 > /dev/null; then
    sudo pkill apache2
fi
