#!/usr/bin/env bash
# Fix the container to run Nginx as the nginx user
# Requirements:
# - Nginx must be running as the nginx user
# - Nginx must listen on all active IPs on port 8080

sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo systemctl restart nginx
ps aux | grep nginx
